'''
    CONTANTES PARA INDICAR A POSIÇÃO DO ELEMENTO DENTRO DO FICHEIRO CSV
'''
COL_COD = 0
COL_NOME_DO_ALIMENTO = 1
COL_NIVEL_1 = 2
COL_NIVEL_2 = 3
COL_NIVEL_3 = 4
COL_ENERGIA_KCAL_ = 5
COL_ENERGIA_KCAL_ESCALA = 6
COL_ENERGIA_KCAL_EDIVEL = 7
COL_ENERGIA_KJ_ = 8
COL_ENERGIA_KJ_ESCALA = 9
COL_ENERGIA_KJ_EDIVEL = 10
COL_LIPIDOS_ = 11
COL_LIPIDOS_ESCALA = 12
COL_LIPIDOS_EDIVEL = 13
COL_ACIDOS_GORDOS_SATURADOS_ = 14
COL_ACIDOS_GORDOS_SATURADOS_ESCALA = 15
COL_ACIDOS_GORDOS_SATURADOS_EDIVEL = 16
COL_ACIDOS_GORDOS_MONOINSATURADOS_ = 17
COL_ACIDOS_GORDOS_MONOINSATURADOS_ESCALA = 18
COL_ACIDOS_GORDOS_MONOINSATURADOS_EDIVEL = 19
COL_ACIDOS_GORDOS_POLINSATURADOS = 20
COL_ACIDOS_GORDOS_POLINSATURADOS_ESCALA = 21
COL_ACIDOS_GORDOS_POLINSATURADOS_EDIVEL = 22
COL_ACIDO_LINOLEICO_ = 23
COL_ACIDO_LINOLEICO_ESCALA = 24
COL_ACIDO_LINOLEICO_EDIVEL = 25
COL_ACIDOS_GORDOS_TRANS = 26
COL_ACIDOS_GORDOS_TRANS_ESCALA = 27
COL_ACIDOS_GORDOS_TRANS_EDIVEL = 28
COL_HIDRATOS_DE_CARBONO = 29
COL_HIDRATOS_DE_CARBONO_ESCALA = 30
COL_HIDRATOS_DE_CARBONO_EDIVEL = 31
COL_MONO_DISSACARIDOS_ACUCARES_ = 32
COL_MONO_DISSACARIDOS_ACUCARES_ESCALA = 33
COL_MONO_DISSACARIDOS_ACUCARES_EDIVEL = 34
COL_OLIGOSSACARIDOS_ = 35
COL_OLIGOSSACARIDOS_ESCALA = 36
COL_OLIGOSSACARIDOS_EDIVEL = 37
COL_AMIDO = 38
COL_AMIDO_ESCALA = 39
COL_AMIDO_EDIVEL = 40
COL_SAL_ = 41
COL_SAL_ESCALA = 42
COL_SAL_EDIVEL = 43
COL_FIBRA_ALIMENTAR = 44
COL_FIBRA_ALIMENTAR_ESCALA = 45
COL_FIBRA_ALIMENTAR_EDIVEL = 46
COL_PROTEINA_ = 47
COL_PROTEINA_ESCALA = 48
COL_PROTEINA_EDIVEL = 49
COL_ALCOOL_ = 50
COL_ALCOOL_ESCALA = 51
COL_ALCOOL_EDIVEL = 52
COL_AGUA_ = 53
COL_AGUA_ESCALA = 54
COL_AGUA_EDIVEL = 55
COL_ACIDOS_ORGANICOS_ = 56
COL_ACIDOS_ORGANICOS_ESCALA = 57
COL_ACIDOS_ORGANICOS_EDIVEL = 58
COL_COLESTEROL = 59
COL_COLESTEROL_ESCALA = 60
COL_COLESTEROL_EDIVEL = 61
COL_VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_ = 62
COL_VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_ESCALA = 63
COL_VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_EDIVEL = 64
COL_CAROTENO = 65
COL_CAROTENO_ESCALA = 66
COL_CAROTENO_EDIVEL = 67
COL_VITAMINA_D = 68
COL_VITAMINA_D_ESCALA = 69
COL_VITAMINA_D_EDIVEL = 70
COL_ALFA_TOCOFEROL = 71
COL_ALFA_TOCOFEROL_ESCALA = 72
COL_ALFA_TOCOFEROL_EDIVEL = 73
COL_TIAMINA_ = 74
COL_TIAMINA_ESCALA = 75
COL_TIAMINA_EDIVEL = 76
COL_RIBOFLAVINA_ = 77
COL_RIBOFLAVINA_ESCALA = 78
COL_RIBOFLAVINA_EDIVEL = 79
COL_NIACINA = 80
COL_NIACINA_ESCALA = 81
COL_NIACINA_EDIVEL = 82
COL_EQUIVALENTES_DE_NIACINA = 83
COL_EQUIVALENTES_DE_NIACINA_ESCALA = 84
COL_EQUIVALENTES_DE_NIACINA_EDIVEL = 85
COL_TRIPTOFANO_60 = 86
COL_TRIPTOFANO_60_ESCALA = 87
COL_TRIPTOFANO_60_EDIVEL = 88
COL_VITAMINA_B6 = 89
COL_VITAMINA_B6_ESCALA = 90
COL_VITAMINA_B6_EDIVEL = 91
COL_VITAMINA_B12 = 92
COL_VITAMINA_B12_ESCALA = 93
COL_VITAMINA_B12_EDIVEL = 94
COL_VITAMINA_C = 95
COL_VITAMINA_C_ESCALA = 96
COL_VITAMINA_C_EDIVEL = 97
COL_FOLATOS = 98
COL_FOLATOS_ESCALA = 99
COL_FOLATOS_EDIVEL = 100
COL_CINZA = 101
COL_CINZA_ESCALA = 102
COL_CINZA_EDIVEL = 103
COL_SODIO = 104
COL_SODIO_ESCALA = 105
COL_SODIO_EDIVEL = 106
COL_POTASSIO_ = 107
COL_POTASSIO_ESCALA = 108
COL_POTASSIO_EDIVEL = 109
COL_CALCIO = 110
COL_CALCIO_ESCALA = 111
COL_CALCIO_EDIVEL = 112
COL_FOSFORO = 113
COL_FOSFORO_ESCALA = 114
COL_FOSFORO_EDIVEL = 115
COL_MAGNESIO = 116
COL_MAGNESIO_ESCALA = 117
COL_MAGNESIO_EDIVEL = 118
COL_FERRO = 119
COL_FERRO_ESCALA = 120
COL_FERRO_EDIVEL = 121
COL_ZINCO = 122
COL_ZINCO_ESCALA = 123

'''
    CONTANTES PARA INDICAR A POSIÇÃO DO ELEMENTO DENTRO DO DICIONÁRIO
'''
DES_COD = 'COD'
DES_NOME_DO_ALIMENTO = 'NOME_DO_ALIMENTO'
DES_NIVEL_1 = 'NIVEL_1_'
DES_NIVEL_2 = 'NIVEL_2'
DES_NIVEL_3 = 'NIVEL_3_'
DES_ENERGIA_KCAL_ = 'ENERGIA_KCAL_'
DES_ENERGIA_KCAL_ESCALA = 'ENERGIA_KCAL_ESCALA'
DES_ENERGIA_KCAL_EDIVEL = 'ENERGIA_KCAL_EDIVEL'
DES_ENERGIA_KJ_ = 'ENERGIA_KJ_'
DES_ENERGIA_KJ_ESCALA = 'ENERGIA_KJ_ESCALA'
DES_ENERGIA_KJ_EDIVEL = 'ENERGIA_KJ_EDIVEL'
DES_LIPIDOS_ = 'LIPIDOS_'
DES_LIPIDOS_ESCALA = 'LIPIDOS_ESCALA'
DES_LIPIDOS_EDIVEL = 'LIPIDOS_EDIVEL'
DES_ACIDOS_GORDOS_SATURADOS_ = 'ACIDOS_GORDOS_SATURADOS_'
DES_ACIDOS_GORDOS_SATURADOS_ESCALA = 'ACIDOS_GORDOS_SATURADOS_ESCALA'
DES_ACIDOS_GORDOS_SATURADOS_EDIVEL = 'ACIDOS_GORDOS_SATURADOS_EDIVEL'
DES_ACIDOS_GORDOS_MONOINSATURADOS_ = 'ACIDOS_GORDOS_MONOINSATURADOS_'
DES_ACIDOS_GORDOS_MONOINSATURADOS_ESCALA = 'ACIDOS_GORDOS_MONOINSATURADOS_ESCALA'
DES_ACIDOS_GORDOS_MONOINSATURADOS_EDIVEL = 'ACIDOS_GORDOS_MONOINSATURADOS_EDIVEL'
DES_ACIDOS_GORDOS_POLINSATURADOS = 'ACIDOS_GORDOS_POLINSATURADOS'
DES_ACIDOS_GORDOS_POLINSATURADOS_ESCALA = 'ACIDOS_GORDOS_POLINSATURADOS_ESCALA'
DES_ACIDOS_GORDOS_POLINSATURADOS_EDIVEL = 'ACIDOS_GORDOS_POLINSATURADOS_EDIVEL'
DES_ACIDO_LINOLEICO_ = 'ACIDO_LINOLEICO_'
DES_ACIDO_LINOLEICO_ESCALA = 'ACIDO_LINOLEICO_ESCALA'
DES_ACIDO_LINOLEICO_EDIVEL = 'ACIDO_LINOLEICO_EDIVEL'
DES_ACIDOS_GORDOS_TRANS = 'ACIDOS_GORDOS_TRANS'
DES_ACIDOS_GORDOS_TRANS_ESCALA = 'ACIDOS_GORDOS_TRANS_ESCALA'
DES_ACIDOS_GORDOS_TRANS_EDIVEL = 'ACIDOS_GORDOS_TRANS_EDIVEL'
DES_HIDRATOS_DE_CARBONO = 'HIDRATOS_DE_CARBONO'
DES_HIDRATOS_DE_CARBONO_ESCALA = 'HIDRATOS_DE_CARBONO_ESCALA'
DES_HIDRATOS_DE_CARBONO_EDIVEL = 'HIDRATOS_DE_CARBONO_EDIVEL'
DES_MONO_DISSACARIDOS_ACUCARES_ = 'MONO_DISSACARIDOS_ACUCARES_'
DES_MONO_DISSACARIDOS_ACUCARES_ESCALA = 'MONO_DISSACARIDOS_ACUCARES_ESCALA'
DES_MONO_DISSACARIDOS_ACUCARES_EDIVEL = 'MONO_DISSACARIDOS_ACUCARES_EDIVEL'
DES_OLIGOSSACARIDOS_ = 'OLIGOSSACARIDOS_'
DES_OLIGOSSACARIDOS_ESCALA = 'OLIGOSSACARIDOS_ESCALA'
DES_OLIGOSSACARIDOS_EDIVEL = 'OLIGOSSACARIDOS_EDIVEL'
DES_AMIDO = 'AMIDO'
DES_AMIDO_ESCALA = 'AMIDO_ESCALA'
DES_AMIDO_EDIVEL = 'AMIDO_EDIVEL'
DES_SAL_ = 'SAL_'
DES_SAL_ESCALA = 'SAL_ESCALA'
DES_SAL_EDIVEL = 'SAL_EDIVEL'
DES_FIBRA_ALIMENTAR = 'FIBRA_ALIMENTAR'
DES_FIBRA_ALIMENTAR_ESCALA = 'FIBRA_ALIMENTAR_ESCALA'
DES_FIBRA_ALIMENTAR_EDIVEL = 'FIBRA_ALIMENTAR_EDIVEL'
DES_PROTEINA_ = 'PROTEINA_'
DES_PROTEINA_ESCALA = 'PROTEINA_ESCALA'
DES_PROTEINA_EDIVEL = 'PROTEINA_EDIVEL'
DES_ALCOOL_ = 'ALCOOL_'
DES_ALCOOL_ESCALA = 'ALCOOL_ESCALA'
DES_ALCOOL_EDIVEL = 'ALCOOL_EDIVEL'
DES_AGUA_ = 'AGUA_'
DES_AGUA_ESCALA = 'AGUA_ESCALA'
DES_AGUA_EDIVEL = 'AGUA_EDIVEL'
DES_ACIDOS_ORGANICOS_ = 'ACIDOS_ORGANICOS_'
DES_ACIDOS_ORGANICOS_ESCALA = 'ACIDOS_ORGANICOS_ESCALA'
DES_ACIDOS_ORGANICOS_EDIVEL = 'ACIDOS_ORGANICOS_EDIVEL'
DES_COLESTEROL = 'COLESTEROL'
DES_COLESTEROL_ESCALA = 'COLESTEROL_ESCALA'
DES_COLESTEROL_EDIVEL = 'COLESTEROL_EDIVEL'
DES_VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_ = 'VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_'
DES_VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_ESCALA = 'VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_ESCALA'
DES_VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_EDIVEL = 'VITAMINA_A_TOTAL_EQUIVALENTES_DE_RETINOL_EDIVEL'
DES_CAROTENO = 'CAROTENO'
DES_CAROTENO_ESCALA = 'CAROTENO_ESCALA'
DES_CAROTENO_EDIVEL = 'CAROTENO_EDIVEL'
DES_VITAMINA_D = 'VITAMINA_D'
DES_VITAMINA_D_ESCALA = 'VITAMINA_D_ESCALA'
DES_VITAMINA_D_EDIVEL = 'VITAMINA_D_EDIVEL'
DES_ALFA_TOCOFEROL = 'ALFA_TOCOFEROL'
DES_ALFA_TOCOFEROL_ESCALA = 'ALFA_TOCOFEROL_ESCALA'
DES_ALFA_TOCOFEROL_EDIVEL = 'ALFA_TOCOFEROL_EDIVEL'
DES_TIAMINA_ = 'TIAMINA_'
DES_TIAMINA_ESCALA = 'TIAMINA_ESCALA'
DES_TIAMINA_EDIVEL = 'TIAMINA_EDIVEL'
DES_RIBOFLAVINA_ = 'RIBOFLAVINA_'
DES_RIBOFLAVINA_ESCALA = 'RIBOFLAVINA_ESCALA'
DES_RIBOFLAVINA_EDIVEL = 'RIBOFLAVINA_EDIVEL'
DES_NIACINA = 'NIACINA'
DES_NIACINA_ESCALA = 'NIACINA_ESCALA'
DES_NIACINA_EDIVEL = 'NIACINA_EDIVEL'
DES_EQUIVALENTES_DE_NIACINA = 'EQUIVALENTES_DE_NIACINA'
DES_EQUIVALENTES_DE_NIACINA_ESCALA = 'EQUIVALENTES_DE_NIACINA_ESCALA'
DES_EQUIVALENTES_DE_NIACINA_EDIVEL = 'EQUIVALENTES_DE_NIACINA_EDIVEL'
DES_TRIPTOFANO_60 = 'TRIPTOFANO_60'
DES_TRIPTOFANO_60_ESCALA = 'TRIPTOFANO_60_ESCALA'
DES_TRIPTOFANO_60_EDIVEL = 'TRIPTOFANO_60_EDIVEL'
DES_VITAMINA_B6 = 'VITAMINA_B6'
DES_VITAMINA_B6_ESCALA = 'VITAMINA_B6_ESCALA'
DES_VITAMINA_B6_EDIVEL = 'VITAMINA_B6_EDIVEL'
DES_VITAMINA_B12 = 'VITAMINA_B12'
DES_VITAMINA_B12_ESCALA = 'VITAMINA_B12_ESCALA'
DES_VITAMINA_B12_EDIVEL = 'VITAMINA_B12_EDIVEL'
DES_VITAMINA_C = 'VITAMINA_C'
DES_VITAMINA_C_ESCALA = 'VITAMINA_C_ESCALA'
DES_VITAMINA_C_EDIVEL = 'VITAMINA_C_EDIVEL'
DES_FOLATOS = 'FOLATOS'
DES_FOLATOS_ESCALA = 'FOLATOS_ESCALA'
DES_FOLATOS_EDIVEL = 'FOLATOS_EDIVEL'
DES_CINZA = 'CINZA'
DES_CINZA_ESCALA = 'CINZA_ESCALA'
DES_CINZA_EDIVEL = 'CINZA_EDIVEL'
DES_SODIO = 'SODIO'
DES_SODIO_ESCALA = 'SODIO_ESCALA'
DES_SODIO_EDIVEL = 'SODIO_EDIVEL'
DES_POTASSIO_ = 'POTASSIO_'
DES_POTASSIO_ESCALA = 'POTASSIO_ESCALA'
DES_POTASSIO_EDIVEL = 'POTASSIO_EDIVEL'
DES_CALCIO = 'CALCIO'
DES_CALCIO_ESCALA = 'CALCIO_ESCALA'
DES_CALCIO_EDIVEL = 'CALCIO_EDIVEL'
DES_FOSFORO = 'FOSFORO'
DES_FOSFORO_ESCALA = 'FOSFORO_ESCALA'
DES_FOSFORO_EDIVEL = 'FOSFORO_EDIVEL'
DES_MAGNESIO = 'MAGNESIO'
DES_MAGNESIO_ESCALA = 'MAGNESIO_ESCALA'
DES_MAGNESIO_EDIVEL = 'MAGNESIO_EDIVEL'
DES_FERRO = 'FERRO'
DES_FERRO_ESCALA = 'FERRO_ESCALA'
DES_FERRO_EDIVEL = 'FERRO_EDIVEL'
DES_ZINCO = 'ZINCO'
DES_ZINCO_ESCALA = 'ZINCO_ESCALA'

FICHEIRO_INSA_TCA = 'DATA/insa_tca.csv'
FICHEIRO_TIPOS_REFEICAO = 'DATA/tipos_refeicao.dat'
FICHEIRO_REFEICOES = 'DATA/refeicoes_'
FICHEIRO_EMENTAS = 'EMENTAS/ementas_'
FICHEIRO_EMENTAS_OUTPUT = 'OUTPUT/ementas_'
FICHEIRO_HTML_EMENTAS = 'MODELOS/ementa.html'
FICHEIRO_FICHA_TECNICA_OUTPUT = 'OUTPUT/ficha_tecnica_'
FICHEIRO_HTML_FICHA_TECNICA = 'MODELOS/ficha_tecnica.html'
DES_SUPERIOR = 'SUPERIOR'
DES_INDEX = 'IDX'

MENU_OPCAO_EMENTA = 'EMENTAS'
MENU_OPCAO_REFEICOES = 'REFEIÇÕES'
MENU_OPCAO_INGREDIENTES = 'INGREDIENTES'
MENU_OPCAO_SAIR = 'SAIR'

MENU_PRINCIPAL = [MENU_OPCAO_EMENTA, MENU_OPCAO_REFEICOES, MENU_OPCAO_INGREDIENTES, MENU_OPCAO_SAIR]

GRID_INGREDIENTES_COLS = [ 
                        ['#', 'INGREDIENTE', 'QTD', 'KCAL', 'KJ', 'LÍP', 'AGS', 'HC', 'PROT', 'SAL', 'AÇÚCAR'],
                        ['', '', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g'],
                        ]
GRID_INGREDIENTES_DIMS = [5, -1, 7, 7, 7, 7, 7, 7, 7, 7, 7]
GRID_INGREDIENTES_ALIGN = ['>','<','>','>','>','>','>','>','>','>','>',]

# Posição das colunas dos detalhes do ingrediente nas refeições
COL_REF_ING_COD = 0
COL_REF_ING_NOME = 1
COL_REF_ING_QTD = 2
COL_REF_ING_ENERGIA_KCAL = 3
COL_REF_ING_ENERGIA_KJ = 4
COL_REF_ING_LIPIDOS= 5
COL_REF_ING_ACS = 6
COL_REF_ING_HC = 7
COL_REF_ING_PROTEINA = 8
COL_REF_ING_SAL = 9
COL_REF_ING_ACUCAR = 10


# Variáveis Globais com toda a informação necessária para aceder aos diversos componentes
listaNivel1 = list()
listaNivel2 = list()
listaNivel3 = list()
listaIngredientes = list()
listaTiposDeRefeicao = list()

# Logotipo de entrada na aplicação
cabecalhoEntrada = [
'                                   █████╗          ',
'                                   ╚════╝          ',
' ██████╗ ███████╗███████╗████████╗ █████╗  ██████╗ ',
'██╔════╝ ██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔═══██╗',
'██║  ███╗█████╗  ███████╗   ██║   ███████║██║   ██║',
'██║   ██║██╔══╝  ╚════██║   ██║   ██╔══██║██║   ██║',
'╚██████╔╝███████╗███████║   ██║   ██║  ██║╚██████╔╝',
' ╚═════╝ ╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ',
]

rodapeEntrada = [
'███████╗███╗   ███╗███████╗███╗   ██╗████████╗ █████╗ ███████╗',
'██╔════╝████╗ ████║██╔════╝████╗  ██║╚══██╔══╝██╔══██╗██╔════╝',
'█████╗  ██╔████╔██║█████╗  ██╔██╗ ██║   ██║   ███████║███████╗',
'██╔══╝  ██║╚██╔╝██║██╔══╝  ██║╚██╗██║   ██║   ██╔══██║╚════██║',
'███████╗██║ ╚═╝ ██║███████╗██║ ╚████║   ██║   ██║  ██║███████║',
'╚══════╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚══════╝',
]


'''
    FUNÇÃO AUXILIAR PARA AJUDAR A PREPARAR AS CONSTANTES A PARTIR DO FICHEIRO TCA
'''
def processar_insa_col():
    handlerFicheiro = open(FICHEIRO_INSA_TCA, 'r', encoding='utf-8')
    temp = handlerFicheiro.readline()
    temp = handlerFicheiro.readline()
    idx = 0
    last = ''
    for item in temp.split(';'):
        proc = item.upper().replace(" ", "_")
        if len(item) == 0:
            proc = last + '_ESCALA'
        for conversao in [['ESCALA_ESCALA', 'EDIVEL'], ['Á', 'A'], ['Â', 'A'], ['-', '_'], ['[', '_'], [']', '_'], ['(', '_'], [')', '_'], ['É', 'E'], ['Í', 'I'], ['Ó', 'O'], ['Ú', 'U'], ['/', '_'], ['Ç', 'C'], ['__', '_'], ['+', '_']]:
            proc = proc.replace(conversao[0], conversao[1])
        print(f'COL_{proc} = {idx}')
        idx += 1
        last = proc

'''
    FUNÇÃO AUXILIAR PARA AJUDAR A PREPARAR AS CONSTANTES A PARTIR DO FICHEIRO TCA
'''
def processar_insa_des():
    handlerFicheiro = open(FICHEIRO_INSA_TCA, 'r', encoding='utf-8')
    temp = handlerFicheiro.readline()
    temp = handlerFicheiro.readline()
    last = ''
    for item in temp.split(';'):
        proc = item.upper().replace(" ", "_")
        if len(item) == 0:
            proc = last + '_ESCALA'
        for conversao in [['ESCALA_ESCALA', 'EDIVEL'], ['Á', 'A'], ['Â', 'A'], ['-', '_'], ['[', '_'], [']', '_'], ['(', '_'], [')', '_'], ['É', 'E'], ['Í', 'I'], ['Ó', 'O'], ['Ú', 'U'], ['/', '_'], ['Ç', 'C'], ['__', '_'], ['+', '_']]:
            proc = proc.replace(conversao[0], conversao[1])
        print(f'DES_{proc} = \'{proc}\'')
        last = proc
